name: easy_loan
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.22.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Design ke liye icons aur images ke liye niche ke packages use kar sakte hain
  # font_awesome_flutter: ^10.7.0 
  # flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Jab aap images aur fonts add karein toh inhein uncomment karein
  # assets:
  #   - assets/images/user_avatar.png
  #   - assets/images/logo.png
  #   - assets/images/coins_icon.png
  #   - assets/images/cash_hand_icon.png
  #   - assets/icons/medical.svg
  #   - assets/icons/education.svg
  #   - assets/icons/travel.svg
  #   - assets/icons/business.svg

  # fonts:
  #   - family: SFPro
  #     fonts:
  #       - asset: assets/fonts/SFProDisplay-Regular.ttf
  #       - asset: assets/fonts/SFProDisplay-Bold.ttf
  #         weight: 700
