name: EasyLoan Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Optimize APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          # Syncing with your requested version
          flutter-version: '3.22.0'
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Optimized APK
        # split-per-abi makes the app run smoother on Unisoc T606 (Itel S23)
        run: flutter build apk --release --split-per-abi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: EasyLoan-Release
          path: build/app/outputs/flutter-apk/app-release.apk
