name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create Project and Icon
        run: |
          flutter create . --overwrite --platforms=android
          # Icons Setup
          for size in mdpi hdpi xhdpi xxhdpi xxxhdpi; do
            mkdir -p android/app/src/main/res/mipmap-$size
            cp 1778294859279_1.png android/app/src/main/res/mipmap-$size/ic_launcher.png
          done
          flutter pub get

      - name: Build Tiny APK (Release Mode)
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: easyloan-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
